# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wikihoops Weekly
slogan: on the past and coming week in the NBA

baseurl: ""
url: "https://weekly.wikihoops.com"
twitter_username: wikihoops
github_username:  wikihoops

timezone: America/New_York

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: wikihoops
      title: "Wikihoops Weekly"
      spoilers: []
      game_recommendations: []
      excerpt_separator: <!--spoilers-->
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  authors:
    output: true

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
